server {
    listen 80;
    server_name wordpress.localhost;

    root /var/www/wordpress;               # Laravel/Symfony: /var/www/myapp/public
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass php85:9000;       # `php85` = the Docker Compose service name
    }
}
